[window]
startup_mode = "Maximized"
decorations = "None"
# opacity = 0.9

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
